# Generated by Django 4.1 on 2022-08-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("lat", models.FloatField(default="")),
                ("lan", models.FloatField(default="")),
                ("location", models.CharField(default="", max_length=50)),
                ("content", models.TextField()),
            ],
        ),
    ]
