# Generated by Django 4.1 on 2022-08-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="marker",
            field=models.CharField(default="", max_length=15),
        ),
    ]
