# Generated by Django 3.2 on 2022-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='content',
        ),
        migrations.AddField(
            model_name='place',
            name='facilities',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='moreinfo',
            field=models.TextField(default=''),
        ),
    ]
